apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
  - name: nagios-api-public
    port: {{ .Values.network.api.port }}
    {{ if .Values.network.api.node_port.enabled }}
      nodePort: {{ .Values.network.api.node_port.port }}
    {{ end }}
  selector:
    app: nagios-api
  {{ if or (.Values.network.api.node_port.enabled) }}
  type: NodePort
  {{ end }}


